site_name: HyperRetailCloud — Formazione Commerciale
site_url: https://ivanrobuschi-custom.github.io/hypercloud-corso-commercial/
site_author: Custom S.p.A.

theme:
  name: material
  logo: assets/icons/logo.png
  favicon: assets/icons/favicon.png
  language: it
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.preview
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.sections
    - navigation.prune
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer
  palette:
    primary: custom

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - attr_list

plugins:
  - search
  - tags

copyright: Copyright Custom S.p.A 2026

nav:
  - Introduzione: introduzione.md
  - Contesto di mercato: contesto_mercato.md
  - Il Prodotto: il_prodotto.md
  - I Piani e i Token: i_piani.md
  - HyperRetailCloud e l'AI: ai.md
  - Il Cliente Tipo: il_cliente_tipo.md
  - Argomentario di Vendita: argomentazioni_di_vendita.md
  - Materiali e Risorse: risorse_e_materiali.md
